server:
  port: 8662

spring:
  application:
    name: gateway-service
  datasource:
    password: root
    url: jdbc:postgresql://postgres:5432/book_shop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-discovery:8761/eureka
  instance:
    hostname: localhost

zuul:
  host:
    connect-timeout-millis: 50000
    socket-timeout-millis: 50000
  ignored-services: '*'
  routes:
    book-service:
      path: /books/**
      serviceId: book-service
      stripPrefix: true

app:
  jwtExpirationMs: 86400000
  jwtSecret: SecretKey

