server:
  port: 8662

spring:
  application:
    name: gateway-service

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

zuul:
  host:
    connect-timeout-millis: 50000
    socket-timeout-millis: 50000
  ignored-services: '*'
  routes:
    auth-service:
      path: /api/**
      serviceId: auth-service
      stripPrefix: true
