version: '3.5'

networks:
  service:
    external:
      name: backend

services:

  dao-service:
    build: dao-microservice
    image: dao-service
    container_name: dao-service
    networks:
      - service
    environment:
      REGISTRY_HOST: kafka:9092
      PSQL_HOST: postgres:5432
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
    expose:
      - 9193
    ports:
      - 9193:9193
    depends_on:
      - zuul-service
    links:
      - zuul-service
    restart: unless-stopped

  zuul-service:
    build: zuul-gateway
    image: zuul-gateway
    container_name: zuul-gateway
    networks:
      - service
    expose:
      - 8662
    ports:
    - 8662:8662
    restart: unless-stopped
    depends_on:
      - eureka-discovery
    links:
      - eureka-discovery

  eureka-discovery:
    build: eureka-server
    image: eureka-server
    container_name: eureka-server
    networks:
      - service
    expose:
      - 8761
    ports:
      - 8761:8761
    restart: unless-stopped
