spring:
  cloud:
    stream:
      bindings:
        input:
          destination: dao-user
        output:
          destination: dao-user


spring.cloud.stream.bindings.output.content-type: application/json
spring.cloud.stream.bindings.input.content-type: application/json
