server:
  port: 9192

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: dao-user
          content-type: application/json
        output:
          destination: dao-user
          content-type: application/json
