server:
  port: 8183

spring:
  application:
    name: book-service
  kafka:
    consumer:
      group-id: fib--group
    producer:
      bootstrap-servers: localhost:9092

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

kafka:
  group:
    id: fib-result-group
  reply:
    topic: book-response
  request:
    topic: book-request

