spring:
  cloud:
    stream:
      bindings:
        input:
          destination: dao-user
  application:
    name: auth-service

server:
  port: 8183

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
